# Generated by Django 6.0.5 on 2026-05-20 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Аллерген',
                'verbose_name_plural': 'Аллергены',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('unit', models.CharField(max_length=20, verbose_name='Ед. измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount_percent', models.PositiveSmallIntegerField(verbose_name='Скидка в %')),
                ('valid_until', models.DateTimeField(verbose_name='Действителен до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('duration', models.PositiveIntegerField(unique=True, verbose_name='Срок подписки(месяцев)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базовая цена (руб/мес)')),
                ('price_coefficient', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Коэффициент цены')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['duration'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('instruction', models.TextField(verbose_name='Инструкция')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Время готовки (мин)')),
                ('calories', models.PositiveIntegerField(verbose_name='Каллории')),
                ('images', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('food_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('dessert', 'Десерт')], max_length=20, verbose_name='Тип еды')),
                ('menu_type', models.CharField(choices=[('classic', 'Классическое'), ('vegan', 'Веганское'), ('keto', 'Кето диета'), ('low_carb', 'Низкоуглеводное')], max_length=20, verbose_name='Тип меню')),
                ('allergens', models.ManyToManyField(blank=True, to='recipes.allergen', verbose_name='Аллергены')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('classic', 'Классическое'), ('vegan', 'Веганское'), ('keto', 'Кето диета'), ('low_carb', 'Низкоуглеводное')], max_length=20, verbose_name='Тип меню')),
                ('persons', models.PositiveIntegerField(verbose_name='Количество персон')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Активирована')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплаченная сумма')),
                ('excluded_allergens', models.ManyToManyField(blank=True, to='recipes.allergen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected', to='recipes.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена (руб)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Ингредиенты в рецептах',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
