# Generated by Django 6.0.5 on 2026-05-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимум использований'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='food_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('dessert', 'Десерт')], db_index=True, max_length=20, verbose_name='Тип еды'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menu_type',
            field=models.CharField(choices=[('classic', 'Классическое'), ('vegan', 'Веганское'), ('keto', 'Кето диета'), ('low_carb', 'Низкоуглеводное')], db_index=True, max_length=20, verbose_name='Тип меню'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='menu_type',
            field=models.CharField(choices=[('classic', 'Классическое'), ('vegan', 'Веганское'), ('keto', 'Кето диета'), ('low_carb', 'Низкоуглеводное')], db_index=True, max_length=20, verbose_name='Тип меню'),
        ),
    ]
