# Generated by Django 6.0.5 on 2026-05-21 10:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_subscription_options_promocode_max_uses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='started_at',
        ),
        migrations.AddField(
            model_name='promocode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Использовано'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активирована'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создана'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='has_breakfast',
            field=models.BooleanField(default=False, verbose_name='Завтраки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='has_dessert',
            field=models.BooleanField(default=False, verbose_name='Десерты'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='has_dinner',
            field=models.BooleanField(default=False, verbose_name='Ужины'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='has_lunch',
            field=models.BooleanField(default=False, verbose_name='Обеды'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='recipes.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает активации'), ('active', 'Активна'), ('expired', 'Истекла'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_before_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость до скидки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая сумма'),
        ),
    ]
