# Generated by Django 6.0.5 on 2026-05-21 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_subscription_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата')),
                ('breakfast', models.ForeignKey(blank=True, limit_choices_to={'food_type': 'breakfast'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipe')),
                ('dessert', models.ForeignKey(blank=True, limit_choices_to={'food_type': 'dessert'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipe')),
                ('dinner', models.ForeignKey(blank=True, limit_choices_to={'food_type': 'dinner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipe')),
                ('lunch', models.ForeignKey(blank=True, limit_choices_to={'food_type': 'lunch'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipe')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='recipes.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': ('Ежедневное меню',),
                'verbose_name_plural': ('Ежедневные меню',),
                'unique_together': {('subscription', 'date')},
            },
        ),
    ]
