# Generated by Django 6.0.5 on 2026-05-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_comment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='confirmation_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа в YooKassa'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Статус оплаты YooKassa'),
        ),
    ]
